  import type { Metadata } from 'next'

  import './globals.css';
import Header from '../app/Comman/header'
  import "bootstrap/dist/css/bootstrap.css";
import login from "../app/login/page";
import Footer from "../app/Comman/footer";

  export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }

  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">
        <body>
        <Header/>
          {children}   
        <Footer/>
    
          </body>
        
      </html>
    )
  }
